receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  clickhousetraces:
    datasource: tcp://cortexsoc_clickhouse:9000
    low_cardinal_exception_grouping: false
  clickhousemetricswrite:
    endpoint: tcp://cortexsoc_clickhouse:9000
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousetraces, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousemetricswrite, logging]
